services:
  web-app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env


  db:
    image: postgres:14.6-alpine
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgresql_data: